window.courseData = {
  project: {
    slug: "rag_api",
    title: "rag_api",
    summary:
      "一个以 file_id 为中心组织文档向量的 RAG 检索服务，重点覆盖索引与检索层，而不是完整聊天层。",
  },
  units: [
    {
      id: 1,
      title: "建立 RAG 与项目的整体认知",
      summary: "先建立边界感，知道这个项目是什么、为什么存在，以及它在完整 RAG 系统中的位置。",
      lessons: [1, 2, 3],
    },
    {
      id: 2,
      title: "吃透文档摄取与预处理",
      summary: "理解文件如何安全进入系统，文本如何被提取、清洗与切块，以及配置如何影响整个摄取链路。",
      lessons: [4, 5, 6, 7],
    },
    {
      id: 3,
      title: "吃透向量化、元数据与检索核心",
      summary: "围绕 chunk、metadata、embedding、向量库与检索接口建立系统化认知。",
      lessons: [8, 9, 10, 11],
    },
    {
      id: 4,
      title: "吃透工程化实现能力",
      summary: "把注意力从 happy path 拉回真实工程场景，理解批处理、回滚、鉴权和性能视角。",
      lessons: [12, 13, 14],
    },
    {
      id: 5,
      title: "通过测试完成整合与扩展",
      summary: "通过测试反向理解设计意图，并把当前检索服务扩展到更完整的 RAG 应用。",
      lessons: [15],
    },
  ],
  sources: [
    {
      title: "README.md",
      description: "先用 README 建立项目定位，不急着记配置细节，只抓职责边界和设计中心。",
      href: "../rag_api/README.md",
    },
    {
      title: "main.py",
      description: "FastAPI 入口、生命周期、线程池与路由挂载都从这里开始。",
      href: "../rag_api/main.py",
    },
    {
      title: "app/config.py",
      description: "配置系统、Embedding Provider 选择、向量库切换都在这里汇总。",
      href: "../rag_api/app/config.py",
    },
    {
      title: "app/routes/document_routes.py",
      description: "上传、切块、入库、检索的主业务链路，教学价值最高。",
      href: "../rag_api/app/routes/document_routes.py",
    },
    {
      title: "app/utils/document_loader.py",
      description: "文件类型识别、编码处理、Loader 分发与 PDF 提取兜底。",
      href: "../rag_api/app/utils/document_loader.py",
    },
    {
      title: "tests/",
      description: "通过测试理解作者真正关心的失败场景和系统边界。",
      href: "../rag_api/tests",
    },
  ],
  lessons: [
    {
      id: 1,
      unit: "单元一",
      title: "RAG 是什么，这个项目到底在做什么",
      description: "建立项目边界感与 RAG 最小闭环认知。",
      goals: [
        "用自己的话解释什么是 RAG",
        "说清 RAG 的最小工作流程",
        "解释这个仓库为什么是一个检索服务而不是聊天应用",
        "理解 file_id 在这个项目中的核心作用",
      ],
      points: [
        "RAG 是先检索，再生成，而不是单纯让模型凭记忆回答",
        "一个最小 RAG 系统包含导入、提取、切块、向量化、检索与生成",
        "rag_api 主要覆盖索引构建和检索服务，不直接覆盖最终答案生成",
        "file_id 是这个项目组织 chunk、过滤检索和业务集成的主线索",
      ],
      readings: ["../rag_api/README.md", "../rag_api/main.py"],
      article: [
        {
          type: "paragraph",
          text: "第 1 课的任务不是马上学会实现细节，而是先建立正确的全局认知。你要先知道 RAG 是什么，这个仓库解决什么问题，以及它不解决什么问题。",
        },
        {
          type: "paragraph",
          text: "RAG 的核心是先找资料，再回答。它不是让大模型直接背诵私有知识，而是让模型在回答前访问外部知识源。",
        },
        {
          type: "image",
          src: "../rag_api/Tutorial/images/lesson-01-rag-flow.svg",
          alt: "RAG 最小工作流程",
          caption: "RAG 最小工作流程",
        },
        {
          type: "paragraph",
          text: "在完整 RAG 系统里，当前仓库更像一个知识检索后端。它负责接收文件、提取文本、切块、生成 embedding、写入向量库，并根据查询做相似度检索。",
        },
        {
          type: "image",
          src: "../rag_api/Tutorial/images/lesson-01-scope.svg",
          alt: "完整 RAG 系统与当前仓库的职责边界",
          caption: "完整 RAG 系统与当前仓库的职责边界",
        },
        {
          type: "paragraph",
          text: "这个项目最关键的业务字段是 file_id。一个文件被拆成多个 chunk 后，这些 chunk 会共享同一个 file_id，因此系统才能按文件过滤、按文件删除和按文件重建索引。",
        },
        {
          type: "image",
          src: "../rag_api/Tutorial/images/lesson-01-file-id.svg",
          alt: "file_id 如何组织同一份文件的多个 Chunk",
          caption: "file_id 如何组织同一份文件的多个 Chunk",
        },
        {
          type: "list",
          items: [
            "先读 README，建立定位",
            "再读 main.py，理解应用入口与生命周期",
            "只回答项目输入、输出、职责、边界、file_id 五个问题",
          ],
        },
      ],
      actions: [
        "写一段 150 到 300 字的笔记，解释这个项目的定位",
        "画出最小 RAG 流程图",
        "用自己的话解释为什么这个仓库强调 file_id",
      ],
    },
    {
      id: 2,
      unit: "单元一",
      title: "本地运行环境与依赖结构",
      description: "从运行层面理解服务依赖与启动方式。",
      goals: ["能把服务真正跑起来", "理解核心依赖各自负责什么", "理解本地运行和 Docker 的差异"],
      points: ["FastAPI 负责 API 服务", "LangChain 负责文档与向量库抽象", "PostgreSQL/pgvector 提供默认向量存储"],
      readings: ["../rag_api/requirements.txt", "../rag_api/docker-compose.yaml", "../rag_api/db-compose.yaml"],
      article: [{ type: "paragraph", text: "这一课会进入运行层面，重点是理解依赖结构与启动方式。建议先分别梳理本地启动和 Docker 启动的路径。" }],
      actions: ["启动项目", "列出运行依赖并分类", "总结每个依赖的角色"],
    },
    {
      id: 3,
      unit: "单元一",
      title: "FastAPI 入口与应用生命周期",
      description: "知道应用如何启动、维护和退出。",
      goals: ["理解 startup 和 shutdown 时发生了什么", "理解线程池的存在理由", "理解数据库连接池的初始化与释放"],
      points: ["FastAPI lifespan", "ThreadPoolExecutor", "资源初始化与资源清理"],
      readings: ["../rag_api/main.py", "../rag_api/app/services/database.py"],
      article: [{ type: "paragraph", text: "这一课重点读 main.py，顺着应用启动路径梳理资源初始化与清理动作。" }],
      actions: ["画出启动时序图", "画出关闭时序图", "解释为什么需要 thread pool"],
    },
    {
      id: 4,
      unit: "单元二",
      title: "配置系统与环境变量设计",
      description: "知道配置如何驱动行为。",
      goals: ["理解配置如何驱动系统行为", "理解 embeddings provider 切换", "理解向量库后端切换"],
      points: ["环境变量分层", "默认值设计", "配置与运行行为的关系"],
      readings: ["../rag_api/app/config.py"],
      article: [{ type: "paragraph", text: "这一课围绕 app/config.py，理解系统如何通过环境变量切换 provider、model 与向量库实现。" }],
      actions: ["把环境变量分组", "列出高优先级配置", "总结默认值策略"],
    },
    {
      id: 5,
      unit: "单元二",
      title: "API 契约与数据模型",
      description: "理解对外接口、请求体和元数据语义。",
      goals: ["理解服务对外暴露的主要能力", "理解请求响应模型", "理解 file_id、entity_id、k 的含义"],
      points: ["Pydantic 模型", "请求校验", "接口设计"],
      readings: ["../rag_api/app/models.py", "../rag_api/app/routes/document_routes.py"],
      article: [{ type: "paragraph", text: "这一课主要整理对外接口，建立调用方视角下的系统认知。" }],
      actions: ["列出接口清单", "为每个接口写输入输出", "说明适用场景"],
    },
    {
      id: 6,
      unit: "单元二",
      title: "文件上传、路径校验与安全摄取",
      description: "理解安全摄取链路。",
      goals: ["理解文件如何安全进入系统", "理解临时文件隔离的必要性", "理解本地嵌入和上传嵌入的区别"],
      points: ["上传链路", "路径穿越防护", "用户隔离临时文件"],
      readings: ["../rag_api/app/routes/document_routes.py"],
      article: [{ type: "paragraph", text: "这一课要顺着上传链路看 validate_file_path 与 _make_unique_temp_path，理解它们为什么重要。" }],
      actions: ["比较 3 个 embed 接口", "总结路径防护策略", "分析多用户上传隔离"],
    },
    {
      id: 7,
      unit: "单元二",
      title: "文档加载器与文本提取链路",
      description: "理解 loader 与文本提取差异。",
      goals: ["理解不同文件类型如何解析", "理解编码探测与转码", "理解 PDF 特殊兜底"],
      points: ["loader 分发", "MIME 与扩展名判断", "文本提取容错"],
      readings: ["../rag_api/app/utils/document_loader.py", "../rag_api/app/routes/document_routes.py"],
      article: [{ type: "paragraph", text: "这一课重点整理文件类型、对应 loader 和常见失败点。" }],
      actions: ["做 loader 对照表", "记录常见失败场景", "比较 PDF 与纯文本提取"],
    },
    {
      id: 8,
      unit: "单元三",
      title: "切块策略与元数据设计",
      description: "围绕 chunk、digest、user_id、file_id 建模。",
      goals: ["理解切块如何发生", "理解 chunk overlap 的作用", "理解 metadata 为检索服务的方式"],
      points: ["RecursiveCharacterTextSplitter", "digest", "file_id 与 user_id"],
      readings: ["../rag_api/app/routes/document_routes.py"],
      article: [{ type: "paragraph", text: "这一课顺着 _prepare_documents_sync 和 store_data_in_vector_db，理解 chunk 与 metadata 是如何形成的。" }],
      actions: ["调整 chunk 参数", "比较 chunk 数量变化", "分析 metadata 的作用"],
    },
    {
      id: 9,
      unit: "单元三",
      title: "Embedding 层抽象",
      description: "理解 provider、model 与接入差异。",
      goals: ["理解 embedding 在项目中的角色", "理解多 provider 统一抽象", "理解 provider 差异"],
      points: ["provider abstraction", "model selection", "credentials"],
      readings: ["../rag_api/app/config.py"],
      article: [{ type: "paragraph", text: "这一课围绕 init_embeddings，看 OpenAI、Azure、HuggingFace 等 provider 是如何被统一起来的。" }],
      actions: ["比较至少 3 种 provider", "总结默认模型", "说明适用场景"],
    },
    {
      id: 10,
      unit: "单元三",
      title: "向量存储抽象与多后端设计",
      description: "理解 pgvector / Atlas Mongo 抽象。",
      goals: ["理解为什么需要 factory", "理解 pgvector 与 Atlas Mongo 的差异", "理解 sync/async 适配"],
      points: ["factory", "backend substitution", "async wrapper"],
      readings: ["../rag_api/app/services/vector_store/factory.py", "../rag_api/app/services/vector_store/async_pg_vector.py", "../rag_api/app/services/vector_store/atlas_mongo_vector.py"],
      article: [{ type: "paragraph", text: "这一课关注存储抽象层，理解为什么系统可以在不同向量库后端之间切换。" }],
      actions: ["画存储抽象图", "比较两个后端", "解释同步与异步的桥接方式"],
    },
    {
      id: 11,
      unit: "单元三",
      title: "检索接口与过滤语义",
      description: "理解 query、query_multiple 和 context。",
      goals: ["理解单文件检索与多文件检索", "理解上下文重建", "理解过滤语义"],
      points: ["/query", "/query_multiple", "/documents/{id}/context"],
      readings: ["../rag_api/app/routes/document_routes.py"],
      article: [{ type: "paragraph", text: "这一课从检索接口视角切入，建立文件级过滤与上下文返回的语义模型。" }],
      actions: ["比较 3 个检索接口", "给出典型调用场景", "分析过滤条件的影响"],
    },
    {
      id: 12,
      unit: "单元四",
      title: "并发、批处理与回滚机制",
      description: "理解系统如何处理大文件和失败场景。",
      goals: ["理解为什么需要批处理", "理解 producer-consumer 管道", "理解回滚时机"],
      points: ["async batching", "sync fallback", "rollback"],
      readings: ["../rag_api/app/routes/document_routes.py"],
      article: [{ type: "paragraph", text: "这一课要读懂批处理逻辑，尤其是部分成功后失败时系统如何清理。" }],
      actions: ["画批处理时序图", "解释失败后的补偿逻辑", "分析内存与吞吐权衡"],
    },
    {
      id: 13,
      unit: "单元四",
      title: "鉴权、授权与多租户视角",
      description: "理解 JWT、request state 与数据隔离。",
      goals: ["理解 JWT 如何进入请求链路", "理解 request.state.user", "理解认证与隔离的差异"],
      points: ["JWT middleware", "authorization", "tenant isolation"],
      readings: ["../rag_api/app/middleware.py", "../rag_api/app/routes/document_routes.py"],
      article: [{ type: "paragraph", text: "这一课关注安全边界：谁能访问、按什么判断、文档数据如何隔离。" }],
      actions: ["梳理授权路径", "比较合法与非法请求", "说明当前模型的局限"],
    },
    {
      id: 14,
      unit: "单元四",
      title: "数据库索引、日志、健康检查与性能视角",
      description: "理解工程性能与运维面。",
      goals: ["理解为什么需要传统索引", "理解日志和健康检查的作用", "理解性能热点"],
      points: ["JSONB/GIN", "health check", "logging", "performance hotspots"],
      readings: ["../rag_api/app/services/database.py", "../rag_api/app/config.py", "../rag_api/app/utils/health.py"],
      article: [{ type: "paragraph", text: "这一课从运维与性能角度理解系统，知道一个请求真正会卡在哪里。" }],
      actions: ["列出潜在瓶颈", "总结索引策略", "说明健康检查价值"],
    },
    {
      id: 15,
      unit: "单元五",
      title: "测试、重构方向与毕业项目",
      description: "用测试读设计，用项目完成整合。",
      goals: ["学会把测试当设计文档来读", "找出扩展点", "完成整合性毕业项目"],
      points: ["route tests", "batch tests", "extension points"],
      readings: ["../rag_api/tests/test_main.py", "../rag_api/tests/test_batch_processing.py", "../rag_api/tests/test_upload_isolation.py"],
      article: [{ type: "paragraph", text: "这一课把测试作为设计说明书，同时思考如何从当前检索服务扩展到完整 RAG 应用。" }],
      actions: ["读测试并总结设计意图", "提出一个扩展方案", "写毕业项目规划"],
    },
  ],
};
